
DBNAME = "EM2"

LOG_FILE_DBNAME = f'{DBNAME}_log'
CSV_FILE_DBNAME = f'{DBNAME}_csv'

CSV_FILE_PATH =  f"data/{DBNAME}/1010123456002_metrics.csv"
LOG_FILE_PATH = f"data/{DBNAME}/xapp-logger.log"


MONGODB_USERNAME="SenseORAN"
MONGODB_PASSWORD="SenseORANFeb21"
MONGODB_CLUSTER="orancluster.5njsvyr"